version: 0.2
phases:
  build:
    commands:
      - aws deploy push --application-name h4b-app --s3-location s3://wanko-artifact/artifact.zip --source source
artifacts:
  files:
    - '**/*'
  base-directory: source